version: "3"
services:
  api:
    build: ./api/.
    ports:
      - "5000:5000"
    volumes:
      - ./:/appdata
    env_file:
      - .env
    networks:
      app-net:
        ipv4_address: 172.19.199.2

  database:
    image: "mongo"
    container_name: "mongodb"
    env_file:
      - .env

    volumes:
      - ./mongo-root-user.js:/docker-entrypoint-initdb.d/mongo-root-user.js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      app-net:
        ipv4_address: ${MONGO_IP}

networks:
  app-net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.199.0/24
