version: '3'
services:
  cultural-awareness:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env

  database:
    image: 'mongo'
    container_name: 'mongodb'
    env_file:
      - .env

    volumes:
      - ./mongo-root-user.js:/docker-entrypoint-initdb.d/mongo-user.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
