name: Api

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Test
        run: |
          pipenv install --dev
          pipenv run pytest

      - name: Lint
        run: |
          # Fail Under 5 because Pylint is very pedantic
          pipenv run pylint api/ --fail-under 5

      - name: Mypy
        run: |
          pipenv run mypy api

      - name: Isort
        run: |
          pipenv run isort -c .

      - name: Docstyle
        run: |
          pipenv run pydocstyle

      - name: Coverage
        run: |
          pipenv run coverage run -m pytest
          pipenv run coveralls
