name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'
          check-latest: true
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
      - run: yarn install
      - run: yarn deploy
