name: Deploy

on:
  push:
    branches:
      - master

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Exec update script
        run: ssh -i ec2-user@18.189.142.71 OSUMC-Cultural-Awareness-App/script/restart-services.sh

  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x

      - run: yarn install
      - run: yarn env:prod
      - run: expo build:web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web-build/
