name: Frontend

on: [push]

jobs:
  CI:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true
      - run: yarn install --dev
      - run: yarn env:dev

      - name: Prettier
        run: |
          yarn run prettier --check frontend

      - name: Typescript
        run: |
          yarn run tsc --build tsconfig.json
